config/routes.rb
Rails.application.routes.draw do












  root :to => 'users#home'

  match 'translations/index', :to => 'translations#index', :as => 'locales_path', :via => :get

  match 'translations/:id', :to => 'translations#update', :via => :put

  match 'translations/:id', :to => 'translations#destroy', :via => :delete

  match 'translations/generate_pos', :to => 'translations#generate_pos', :via => :post

  match 'translations/generation_status', :to => 'translations#generation_status', :via => :get

  match 'translations/upload_po', :to => 'translations#upload_po'

  match 'translations/get_po/:locale', :to => 'translations#get_po', :via => :get

  match 'translations/delete_po/:locale', :to => 'translations#delete_po', :via => :delete



  match ':controller(/:action(/:id))(.:format)'

end

app/models/user.rb
# encoding: utf-8
################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Thu Oct 31 16:41:16 +0100 2013
## It should be placed at 'app/models/user.rb'
## All manual modifications will be destroyed on next generation
################################################


class User < ActiveRecord::Base

  self.table_name = 'users'

  SEARCHABLE_FIELDS = [:login,:customers,:telephone,:dev_feedbacks,:file_imports].freeze
  RESTRICTED_FIELDS = [].freeze
  FIELDS = HashWithIndifferentAccess.new(:login => :string, :first_name => :string, :last_name => :string, :email => :string, :customers => :hm_assoc, :telephone => :string, :language => :string, :active => :boolean, :hashed_password => :string, :salt => :string, :last_login => :datetime, :last_session_id => :string, :user_accesses => :hm_assoc, :profiles => :habtm_assoc, :dev_feedbacks => :hm_assoc, :file_imports => :hm_assoc).freeze
  COMPARATORS = {:login => ActiveSupport::OrderedHash['=~', ["users.login LIKE ?", '%%%s%'], '!~', ["users.login NOT LIKE ?", '%%%s%'], '^=', ["users.login LIKE ?", '%s%'], '$=', ["users.login LIKE ?", '%%%s'], '=', ["users.login = ?"], '!=', ["users.login <> ?"], 'NULL', ["users.login IS NULL", ''], 'NOT_NULL', ["users.login IS NOT NULL", '']],
    :first_name => ActiveSupport::OrderedHash['=~', ["users.first_name LIKE ?", '%%%s%'], '!~', ["users.first_name NOT LIKE ?", '%%%s%'], '^=', ["users.first_name LIKE ?", '%s%'], '$=', ["users.first_name LIKE ?", '%%%s'], '=', ["users.first_name = ?"], '!=', ["users.first_name <> ?"], 'NULL', ["users.first_name IS NULL", ''], 'NOT_NULL', ["users.first_name IS NOT NULL", '']],
    :last_name => ActiveSupport::OrderedHash['=~', ["users.last_name LIKE ?", '%%%s%'], '!~', ["users.last_name NOT LIKE ?", '%%%s%'], '^=', ["users.last_name LIKE ?", '%s%'], '$=', ["users.last_name LIKE ?", '%%%s'], '=', ["users.last_name = ?"], '!=', ["users.last_name <> ?"], 'NULL', ["users.last_name IS NULL", ''], 'NOT_NULL', ["users.last_name IS NOT NULL", '']],
    :email => ActiveSupport::OrderedHash['=~', ["users.email LIKE ?", '%%%s%'], '!~', ["users.email NOT LIKE ?", '%%%s%'], '^=', ["users.email LIKE ?", '%s%'], '$=', ["users.email LIKE ?", '%%%s'], '=', ["users.email = ?"], '!=', ["users.email <> ?"], 'NULL', ["users.email IS NULL", ''], 'NOT_NULL', ["users.email IS NOT NULL", '']],
    :customers => ActiveSupport::OrderedHash['IN', ["customers.id IN (?)"], 'NOT_IN', ["customers.id NOT IN (?)"]],
    :telephone => ActiveSupport::OrderedHash['=~', ["users.telephone LIKE ?", '%%%s%'], '!~', ["users.telephone NOT LIKE ?", '%%%s%'], '^=', ["users.telephone LIKE ?", '%s%'], '$=', ["users.telephone LIKE ?", '%%%s'], '=', ["users.telephone = ?"], '!=', ["users.telephone <> ?"], 'NULL', ["users.telephone IS NULL", ''], 'NOT_NULL', ["users.telephone IS NOT NULL", '']],
    :language => ActiveSupport::OrderedHash['=~', ["users.language LIKE ?", '%%%s%'], '!~', ["users.language NOT LIKE ?", '%%%s%'], '^=', ["users.language LIKE ?", '%s%'], '$=', ["users.language LIKE ?", '%%%s'], '=', ["users.language = ?"], '!=', ["users.language <> ?"], 'NULL', ["users.language IS NULL", ''], 'NOT_NULL', ["users.language IS NOT NULL", '']],
    :active => ActiveSupport::OrderedHash['=', ["users.active = ?"], '!=', ["users.active <> ?"], 'NULL', ["users.active IS NULL", ''], 'NOT_NULL', ["users.active IS NOT NULL", '']],
    :hashed_password => ActiveSupport::OrderedHash['=~', ["users.hashed_password LIKE ?", '%%%s%'], '!~', ["users.hashed_password NOT LIKE ?", '%%%s%'], '^=', ["users.hashed_password LIKE ?", '%s%'], '$=', ["users.hashed_password LIKE ?", '%%%s'], '=', ["users.hashed_password = ?"], '!=', ["users.hashed_password <> ?"], 'NULL', ["users.hashed_password IS NULL", ''], 'NOT_NULL', ["users.hashed_password IS NOT NULL", '']],
    :salt => ActiveSupport::OrderedHash['=~', ["users.salt LIKE ?", '%%%s%'], '!~', ["users.salt NOT LIKE ?", '%%%s%'], '^=', ["users.salt LIKE ?", '%s%'], '$=', ["users.salt LIKE ?", '%%%s'], '=', ["users.salt = ?"], '!=', ["users.salt <> ?"], 'NULL', ["users.salt IS NULL", ''], 'NOT_NULL', ["users.salt IS NOT NULL", '']],
    :last_login => ActiveSupport::OrderedHash['=', ["users.last_login = ?"], '!=', ["users.last_login <> ?"], '>', ["users.last_login > ?"], '<', ["users.last_login < ?"], '>=', ["users.last_login >= ?"], '<=', ["users.last_login <= ?"]],
    :last_login_min => ActiveSupport::OrderedHash['>=', ["users.last_login >= ?"], '>', ["users.last_login > ?"]],
    :last_login_max => ActiveSupport::OrderedHash['<=', ["users.last_login <= ?"], '<', ["users.last_login < ?"]],
    :last_session_id => ActiveSupport::OrderedHash['=~', ["users.last_session_id LIKE ?", '%%%s%'], '!~', ["users.last_session_id NOT LIKE ?", '%%%s%'], '^=', ["users.last_session_id LIKE ?", '%s%'], '$=', ["users.last_session_id LIKE ?", '%%%s'], '=', ["users.last_session_id = ?"], '!=', ["users.last_session_id <> ?"], 'NULL', ["users.last_session_id IS NULL", ''], 'NOT_NULL', ["users.last_session_id IS NOT NULL", '']],
    :user_accesses => ActiveSupport::OrderedHash['IN', ["user_accesses.id IN (?)"], 'NOT_IN', ["user_accesses.id NOT IN (?)"]],
    :profiles => ActiveSupport::OrderedHash['IN', ["profiles_users.profile_id IN (?)"], 'NOT_IN', ["profiles_users.profile_id NOT IN (?)"]],
    :dev_feedbacks => ActiveSupport::OrderedHash['IN', ["dev_feedbacks.id IN (?)"], 'NOT_IN', ["dev_feedbacks.id NOT IN (?)"]],
    :file_imports => ActiveSupport::OrderedHash['IN', ["file_imports.id IN (?)"], 'NOT_IN', ["file_imports.id NOT IN (?)"]],
  :accesses => ActiveSupport::OrderedHash['IN', [". IN (?)"], 'NOT_IN', [". NOT IN (?)"]]}.freeze

  FILES_DEST = Rails.root.join('files', %q{users}).to_s


  # == Validations


  validates_presence_of(:login)
  validates_uniqueness_of(:login, :case_sensitive => false)
  validates_presence_of(:email)

  def self.validates_as_email_243_for_email(field, options = {})
    pattern = /\A(|(([A-Za-z0-9]+_+)|([A-Za-z0-9]+\-+)|([A-Za-z0-9]+\.+)|([A-Za-z0-9]+\++))*[A-Za-z0-9]+@((\w+\-+)|(\w+\.))*\w{1,63}\.[a-zA-Z]{2,6})\Z/i

    # validates length

    email_len_opts = options.merge(:in => (3)..(320))
    validates_length_of :email, email_len_opts

    # validates format

    email_fmt_opts = options.merge({:with => pattern,
    :message => (options['wrong_format'] || options['message'] || _('%{value} is not a valid email address')) })
    validates_format_of :email, email_fmt_opts
  end
  validates_as_email_243_for_email(:email)


  # == Triggers


  before_create(:set_default_profiles)
  before_validation(:set_default_password, :on => :create)
  after_create(:email_welcome_and_pass)


  # == Relations
  #


  has_many :customers, :foreign_key => "user_id", :class_name => "Customer"
  has_many :user_accesses, :dependent => :destroy, :foreign_key => "user_id", :class_name => "UserAccess"
  has_many :dev_feedbacks, :foreign_key => "user_id", :class_name => "DevFeedback"
  has_many :file_imports, :foreign_key => "user_id", :class_name => "FileImport"
  has_and_belongs_to_many :profiles, :association_foreign_key => "profile_id", :join_table => "profiles_users", :foreign_key => "user_id", :class_name => "Profile"
  has_many :accesses, :source => :access, :through => :user_accesses


  # Associations through specific setters
  #



  def accesses=(array)
    ids = array.map(&:id)
    UserAccess.where(['user_accesses.user_id = ? AND user_accesses.access_id NOT IN (?)', self.id, ids]).select(:id).each(&:destroy)
    user_access_ids = UserAccess.all(:conditions => {:user_id => self.id, :access_id => ids}, :select => 'access_id').map(&:access_id)
    (ids - user_access_ids).each{|i|
      UserAccess.create(:user_id => self.id, :access_id => i)
    }
    self.accesses.reload
  end

  # Virtual Fields

  attr_accessor :password

  attr_accessor :customers_was
  attr_accessor :user_accesses_was
  attr_accessor :accesses_was
  attr_accessor :profiles_was
  attr_accessor :dev_feedbacks_was
  attr_accessor :file_imports_was


  # == Methods
  #



  # Load the matching object with right attributes.
  #
  # Author:: Sylvain Abélard
  # Version:: 53
  # Last Update:: 2013-09-03 16:56:08 UTC
  # Status:: Validated


  def self.load_from_params(att)
    return User.new if att.blank?
    std_atts = att.reject{|k,v| %w(id customers user_accesses accesses profiles dev_feedbacks file_imports).include?(k.to_s) }
    user = nil
    if att.has_key?(:id) && att[:id].to_i != 0 # Useful for HasOne (ho_assoc)
      user = User.find(att[:id])
      user.attributes = std_atts
    else
      user = User.new(std_atts)
    end

    # clean associations

    user.customers_load_from_params(att[:customers])
    user.user_accesses_load_from_params(att[:user_accesses])
    user.accesses_load_from_params(att[:accesses])
    user.profiles_load_from_params(att[:profiles])
    user.dev_feedbacks_load_from_params(att[:dev_feedbacks])
    user.file_imports_load_from_params(att[:file_imports])

    #clean binaries
    #clean serialized data

    return user
  end


  # Search
  #
  # Author:: Yann Azoury
  # Version:: 23
  # Last Update:: 2011-08-09 11:16:42 UTC

app/views/users/_access_graph.dot.erb
digraph G {
  "<%= @user.disp_name %>";

<% @user.profiles.each do |p| %>
	"<%= p.name %>" [color=darkblue];
	"<%= @user.disp_name %>" -> "<%= p.name %>";
<% end %>

<% (@user_accesses | @profile_accesses).group_by(&:table_sid).each do |t, pas| %>
	table_<%= t %> [
		label="{<%= _(t.titleize) + '|' + pas.collect{|a| %Q(<#{a.id}> #{a.disp_name}) }.join('|') %>}"
		shape="record"
		color=darkgreen
	];
<% end %>

<% @user.profiles.each do |p| %>
<% p.accesses.each do |a| %>
	"<%= p.name %>" -> table_<%= a.table_sid %>:<%= a.id %>;<% end %>
<% end %>

<% @user_accesses.each do |ua| %>
	"<%= @user.disp_name %>" -> table_<%= ua.table_sid %>:<%= ua.id %>;<% end %>

  bgcolor = "transparent";

  node [
    shape = "record"
    style = "filled"
    fontname = "Verdana"
    fontsize = 9
  ]
}

app/views/users/_field_access_graph.dot.erb
digraph G {
  "<%= @user.disp_name %>";

<% @user.profiles.each do |p| %>
	"<%= p.name %>" [color=darkblue];
	"<%= @user.disp_name %>" -> "<%= p.name %>";
<% end %>

<% (@user_accesses | @profile_accesses).group_by(&:table_sid).each do |t, pas| %>
	table_<%= t %> [
		label="{<%= _(t.titleize) + '|' + pas.map{|a| %Q(<#{a.id}> #{a.disp_name}) }.join('|') %>}"
		shape="record"
		color=darkgreen
	];
<% end %>

<% @user.profiles.each do |p| %>
<% p.accesses.each do |a|
  pa = a.profile_accesses.first(:conditions => {:profile_id => p.id, 'profile_accesses.read' => true, 'profile_accesses.write' => true})
  next if pa.nil?
  lab = pa.read? ? "Read" : ""
  lab = pa.write? ? "Write" : ""
  lab = "Read & Write" if pa.read? && pa.write? %>
	"<%= p.name %>" -> table_<%= a.table_sid %>:<%= a.id %> [label="<%= lab %>" labeldistance="4.0"];<% end %>
<% end %>

<% @user_accesses.each do |ua|
  pa = ua.user_accesses.first(:conditions => {:user_id => @user.id}) 
  lab = pa.read? ? "Read" : ""
  lab = pa.write? ? "Write" : ""
  lab = "Read & Write" if pa.read? && pa.write? %>
	"<%= @user.disp_name %>" -> table_<%= ua.table_sid %>:<%= ua.id %> [label="<%= lab %>" labeldistance="4.0"];<% end %>

  bgcolor = "transparent";

  node [
    shape = "record"
    style = "filled"
    fontname = "Verdana"
    fontsize = 9
  ]
}

app/views/users/_importer_threads.html.erb
<%;################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Thu Oct 15 01:21:19 +0200 2009
## It should be placed at 'app/views/users/_importer_threads.html.erb'
## All manual modifications will be destroyed on next generation
################################################ 
-%>
<% if @importer_thread
 imp = @importer_thread %>
<div class='overlay_dark'></div>
<div class='overlay_text'>
  <%= _(%q{Importer currently running...}) %><br />
  <img style="align:center" src="/images/std/indicator.gif" />
  <span id='status_percent'><%= imp[:percent] %>&#37;</span>
</div>
<% end %>


app/views/users/search.html.erb
<%;################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Thu Oct 31 16:41:19 +0100 2013
## It should be placed at 'app/views/users/search.html.erb'
## All manual modifications will be destroyed on next generation
################################################ %>
<h2 class="title"><img src="/images/page_icons/magnifier.png" alt="<%= _(%q{Search}) %>" /> <%= _("Searching %{page}") % {:page => _("User")} %> </h2>


<div id="container" class="content align_fields">
<div class="fields">
<form action="<%= "/#{params[:lang]}" if params[:lang] %>/users/search" data-update="search_results" id="users_search_form" method="post">
	<fieldset style="border:none;" id="user_<%=  @user.id || 0  %>_root_container" >
<label class="input_string" data-field="login" for="login_for" id="users_login_<%= @user.id || 0 %>"><%= s_(%q{Login: }) %><select class="not-aligned comparator" id="comp_login" name="comp_login"><%= options_for_select([['','']]+(User::COMPARATORS[:login] || {}).keys.map{|k| [s_("string|#{k}"), k]}) %></select>
<input id="user_<%= @user.id || 0 %>_login" maxlength="255" name="user[<%=  @user.id || 0  %>][login]" type="text" value="<%=h @user.login %>" /></label>
<label class="input_string" data-field="first_name" for="first_name_for" id="users_first_name_<%= @user.id || 0 %>"><%= s_(%q{First Name: }) %><select class="not-aligned comparator" id="comp_first_name" name="comp_first_name"><%= options_for_select([['','']]+(User::COMPARATORS[:first_name] || {}).keys.map{|k| [s_("string|#{k}"), k]}) %></select>
<input id="user_<%= @user.id || 0 %>_first_name" maxlength="255" name="user[<%=  @user.id || 0  %>][first_name]" type="text" value="<%=h @user.first_name %>" /></label>
<label class="input_string" data-field="last_name" for="last_name_for" id="users_last_name_<%= @user.id || 0 %>"><%= s_(%q{Last Name: }) %><select class="not-aligned comparator" id="comp_last_name" name="comp_last_name"><%= options_for_select([['','']]+(User::COMPARATORS[:last_name] || {}).keys.map{|k| [s_("string|#{k}"), k]}) %></select>
<input id="user_<%= @user.id || 0 %>_last_name" maxlength="255" name="user[<%=  @user.id || 0  %>][last_name]" type="text" value="<%=h @user.last_name %>" /></label>
<label class="input_string" data-field="email" for="email_for" id="users_email_<%= @user.id || 0 %>"><%= s_(%q{Email: }) %><select class="not-aligned comparator" id="comp_email" name="comp_email"><%= options_for_select([['','']]+(User::COMPARATORS[:email] || {}).keys.map{|k| [s_("string|#{k}"), k]}) %></select>
<input id="user_<%= @user.id || 0 %>_email" maxlength="255" name="user[<%=  @user.id || 0  %>][email]" type="text" value="<%=h @user.email %>" /></label>
<label class="input_hm_assoc" data-field="customers" for="customers_for" id="users_customers_<%= @user.id || 0 %>"><%= s_(%q{Customers: }) %><select class="not-aligned comparator" id="comp_customers" name="comp_customers"><%= options_for_select([['','']]+(User::COMPARATORS[:customers] || {}).keys.map{|k| [s_("association|#{k}"), k]}) %></select>
<select multiple="true" size="8" name="user[<%=  @user.id || 0  %>][customers][]" id="user_<%= @user.id || 0 %>_customers">
<option value=""><%= _(%q{[All]}) %></option>
<%= options_for_select((@user_customers__potential_values || @user.customers__potential_values).map{|p| [p.disp_name, p.id] }, @user.customer_ids) %>
</select></label>
<label class="input_string" data-field="telephone" for="telephone_for" id="users_telephone_<%= @user.id || 0 %>"><%= s_(%q{Telephone: }) %><select class="not-aligned comparator" id="comp_telephone" name="comp_telephone"><%= options_for_select([['','']]+(User::COMPARATORS[:telephone] || {}).keys.map{|k| [s_("string|#{k}"), k]}) %></select>
<input id="user_<%= @user.id || 0 %>_telephone" maxlength="255" name="user[<%=  @user.id || 0  %>][telephone]" type="text" value="<%=h @user.telephone %>" /></label>
<label class="input_string" data-field="language" for="language_for" id="users_language_<%= @user.id || 0 %>"><%= s_(%q{Language: }) %><select class="not-aligned comparator" id="comp_language" name="comp_language"><%= options_for_select([['','']]+(User::COMPARATORS[:language] || {}).keys.map{|k| [s_("string|#{k}"), k]}) %></select>
<select id="user_<%= @user.id || 0 %>_language" name="user[<%=  @user.id || 0  %>][language]"><%= options_for_select(@user_language__potential_values || @user.language__potential_values, @user.language) %></select></label>
<label class="input_boolean" data-field="active" for="active_for" id="users_active_<%= @user.id || 0 %>"><%= s_(%q{Active: }) %><select class="not-aligned comparator" id="comp_active" name="comp_active"><%= options_for_select([['','']]+(User::COMPARATORS[:active] || {}).keys.map{|k| [s_("boolean|#{k}"), k]}) %></select>
<select id="user_<%=  @user.id || 0  %>_active" name="user[<%=  @user.id || 0  %>][active]"><option value=""><%=  %></option>
<option value="1"><%= _(%q{true}) %></option>
<option value="0"><%= _(%q{false}) %></option></select></label>

<fieldset id="user_<%=  @user.id || 0  %>_access_management" >
<legend for="user_<%=  @user.id || 0  %>_access_management" id="users_access_management_<%= @user.id || 0 %>"><%= s_(%q{Access Management}) %></legend>


<label class="input_habtm_assoc" data-field="profiles" for="profiles_for" id="users_profiles_<%= @user.id || 0 %>"><%= s_(%q{Profiles: }) %><select class="not-aligned comparator" id="comp_profiles" name="comp_profiles"><%= options_for_select([['','']]+(User::COMPARATORS[:profiles] || {}).keys.map{|k| [s_("association|#{k}"), k]}) %></select>
<select title="Profiles Accesses are combined." multiple="true" size="8" name="user[<%=  @user.id || 0  %>][profiles][]" id="user_<%= @user.id || 0 %>_profiles">
<option value=""><%= _(%q{[All]}) %></option>
<%= options_for_select((@user_profiles__potential_values || @user.profiles__potential_values).map{|p| [p.disp_name, p.id] }, @user.profile_ids) %>
</select></label>
</fieldset>

<fieldset id="user_<%=  @user.id || 0  %>_application_usage" >
<legend for="user_<%=  @user.id || 0  %>_application_usage" id="users_application_usage_<%= @user.id || 0 %>"><%= s_(%q{Application Usage}) %></legend>
<label class="input_hm_assoc" data-field="dev_feedbacks" for="dev_feedbacks_for" id="users_dev_feedbacks_<%= @user.id || 0 %>"><%= s_(%q{Dev Feedbacks: }) %><select class="not-aligned comparator" id="comp_dev_feedbacks" name="comp_dev_feedbacks"><%= options_for_select([['','']]+(User::COMPARATORS[:dev_feedbacks] || {}).keys.map{|k| [s_("association|#{k}"), k]}) %></select>
<select multiple="true" size="8" name="user[<%=  @user.id || 0  %>][dev_feedbacks][]" id="user_<%= @user.id || 0 %>_dev_feedbacks">
<option value=""><%= _(%q{[All]}) %></option>
<%= options_for_select((@user_dev_feedbacks__potential_values || @user.dev_feedbacks__potential_values).map{|r| ['~~' * r.level + " #{r.disp_name}", r.id]}, @user.dev_feedback_ids) %>
</select></label>

</fieldset>

</fieldset>

  <input disable_with="" id="search_search_form_submit" name="commit" type="submit" value="<%= _(%q{Search}) %>" />
</form>
</div>
<div id="search_results"></div>
</div>

<% if @pres_mode == :list_zoom %>
<a href="#" data-method="get" onclick="new Ajax.Updater('users_element', '<%= "/#{params[:lang]}" if params[:lang] %>/users/index', {asynchronous:true, evalScripts:true}); return false;" rel="nofollow" title="<%= _(%q{Index of all users.}) %>"><img src="/images/page_icons/user.png" alt="<%= _(%q{Back}) %>" title="<%= _(%q{Back}) %>"/> <%= _(%q{Back}) %></a>
<% else %>
<a href="<%= "/#{params[:lang]}" if params[:lang] %>/users/index" data-method="get" rel="nofollow" title="<%= _(%q{Index of all users.}) %>"><img src="/images/page_icons/user.png" alt="<%= _(%q{Back}) %>" title="<%= _(%q{Back}) %>"/> <%= _(%q{Back}) %></a>
<% end %>


<script type="text/javascript">
//<![CDATA[



function onready_search_call() {

$('#users_search_form').on('submit', function(evt) {
  var upd = $(this).data('update');
  evt.preventDefault();
  $.post(this.action, {query:Storage.jsonify_form(this)}).success(function(r) { $('#'+upd).html(r); });
})

}
<% if request.xhr? %>onready_search_call();<% else %> if (document.observe) {
document.observe('dom:loaded', onready_search_call)
} else if (typeof(jQuery) != 'undefined') {
jQuery(document).ready(onready_search_call)
}<% end %>




//]]>
</script>