config/routes.rb
Rails.application.routes.draw do












  root :to => 'users#home'

  match 'translations/index', :to => 'translations#index', :as => 'locales_path', :via => :get

  match 'translations/:id', :to => 'translations#update', :via => :put

  match 'translations/:id', :to => 'translations#destroy', :via => :delete

  match 'translations/generate_pos', :to => 'translations#generate_pos', :via => :post

  match 'translations/generation_status', :to => 'translations#generation_status', :via => :get

  match 'translations/upload_po', :to => 'translations#upload_po'

  match 'translations/get_po/:locale', :to => 'translations#get_po', :via => :get

  match 'translations/delete_po/:locale', :to => 'translations#delete_po', :via => :delete



  match ':controller(/:action(/:id))(.:format)'

end

app/models/file_import.rb
# encoding: utf-8
################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Fri Oct 18 12:04:12 +0200 2013
## It should be placed at 'app/models/file_import.rb'
## All manual modifications will be destroyed on next generation
################################################


class FileImport < ActiveRecord::Base

  self.table_name = 'file_imports'

  SEARCHABLE_FIELDS = [:user,:file_import,:re_imports,:started_at,:completed_at,:read_lines,:wrote_records,:expected_total,:error_count,:log].freeze
  RESTRICTED_FIELDS = [].freeze
  FIELDS = HashWithIndifferentAccess.new(:user => :bt_assoc, :file => :binary, :file_import => :bt_assoc, :re_imports => :hm_assoc, :started_at => :datetime, :completed_at => :datetime, :read_lines => :integer, :wrote_records => :integer, :expected_total => :integer, :error_count => :integer, :log => :text).freeze
  COMPARATORS = {:user => ActiveSupport::OrderedHash['=', ["file_imports.user_id = ?"], '!=', ["file_imports.user_id <> ?"], 'NULL', ["file_imports.user_id IS NULL", ''], 'NOT_NULL', ["file_imports.user_id IS NOT NULL", '']],
    :user_id => ActiveSupport::OrderedHash['=', ["file_imports.user_id = ?"], '!=', ["file_imports.user_id <> ?"], 'NULL', ["file_imports.user_id IS NULL", ''], 'NOT_NULL', ["file_imports.user_id IS NOT NULL", '']],
    :file => ActiveSupport::OrderedHash['=~', ["file_imports.file__name LIKE ?", '%%%s%'], '!~', ["file_imports.file__name NOT LIKE ?", '%%%s%'], '^=', ["file_imports.file__name LIKE ?", '%s%'], '$=', ["file_imports.file__name LIKE ?", '%%%s'], '=', ["file_imports.file__name = ?"], '!=', ["file_imports.file__name <> ?"], 'NULL', ["file_imports.file__name IS NULL", ''], 'NOT_NULL', ["file_imports.file__name IS NOT NULL", '']],
    :file_import => ActiveSupport::OrderedHash['=', ["file_imports.file_import_id = ?"], '!=', ["file_imports.file_import_id <> ?"], 'NULL', ["file_imports.file_import_id IS NULL", ''], 'NOT_NULL', ["file_imports.file_import_id IS NOT NULL", '']],
    :file_import_id => ActiveSupport::OrderedHash['=', ["file_imports.file_import_id = ?"], '!=', ["file_imports.file_import_id <> ?"], 'NULL', ["file_imports.file_import_id IS NULL", ''], 'NOT_NULL', ["file_imports.file_import_id IS NOT NULL", '']],
    :re_imports => ActiveSupport::OrderedHash['IN', ["file_imports.id IN (?)"], 'NOT_IN', ["file_imports.id NOT IN (?)"]],
    :started_at => ActiveSupport::OrderedHash['=', ["file_imports.started_at = ?"], '!=', ["file_imports.started_at <> ?"], '>', ["file_imports.started_at > ?"], '<', ["file_imports.started_at < ?"], '>=', ["file_imports.started_at >= ?"], '<=', ["file_imports.started_at <= ?"]],
    :started_at_min => ActiveSupport::OrderedHash['>=', ["file_imports.started_at >= ?"], '>', ["file_imports.started_at > ?"]],
    :started_at_max => ActiveSupport::OrderedHash['<=', ["file_imports.started_at <= ?"], '<', ["file_imports.started_at < ?"]],
    :completed_at => ActiveSupport::OrderedHash['=', ["file_imports.completed_at = ?"], '!=', ["file_imports.completed_at <> ?"], '>', ["file_imports.completed_at > ?"], '<', ["file_imports.completed_at < ?"], '>=', ["file_imports.completed_at >= ?"], '<=', ["file_imports.completed_at <= ?"]],
    :completed_at_min => ActiveSupport::OrderedHash['>=', ["file_imports.completed_at >= ?"], '>', ["file_imports.completed_at > ?"]],
    :completed_at_max => ActiveSupport::OrderedHash['<=', ["file_imports.completed_at <= ?"], '<', ["file_imports.completed_at < ?"]],
    :read_lines => ActiveSupport::OrderedHash['=', ["file_imports.read_lines = ?"], '!=', ["file_imports.read_lines <> ?"], '>', ["file_imports.read_lines > ?"], '<', ["file_imports.read_lines < ?"], '>=', ["file_imports.read_lines >= ?"], '<=', ["file_imports.read_lines <= ?"]],
    :read_lines_min => ActiveSupport::OrderedHash['>=', ["file_imports.read_lines >= ?"], '>', ["file_imports.read_lines > ?"]],
    :read_lines_max => ActiveSupport::OrderedHash['<=', ["file_imports.read_lines <= ?"], '<', ["file_imports.read_lines < ?"]],
    :wrote_records => ActiveSupport::OrderedHash['=', ["file_imports.wrote_records = ?"], '!=', ["file_imports.wrote_records <> ?"], '>', ["file_imports.wrote_records > ?"], '<', ["file_imports.wrote_records < ?"], '>=', ["file_imports.wrote_records >= ?"], '<=', ["file_imports.wrote_records <= ?"]],
    :wrote_records_min => ActiveSupport::OrderedHash['>=', ["file_imports.wrote_records >= ?"], '>', ["file_imports.wrote_records > ?"]],
    :wrote_records_max => ActiveSupport::OrderedHash['<=', ["file_imports.wrote_records <= ?"], '<', ["file_imports.wrote_records < ?"]],
    :expected_total => ActiveSupport::OrderedHash['=', ["file_imports.expected_total = ?"], '!=', ["file_imports.expected_total <> ?"], '>', ["file_imports.expected_total > ?"], '<', ["file_imports.expected_total < ?"], '>=', ["file_imports.expected_total >= ?"], '<=', ["file_imports.expected_total <= ?"]],
    :expected_total_min => ActiveSupport::OrderedHash['>=', ["file_imports.expected_total >= ?"], '>', ["file_imports.expected_total > ?"]],
    :expected_total_max => ActiveSupport::OrderedHash['<=', ["file_imports.expected_total <= ?"], '<', ["file_imports.expected_total < ?"]],
    :error_count => ActiveSupport::OrderedHash['=', ["file_imports.error_count = ?"], '!=', ["file_imports.error_count <> ?"], '>', ["file_imports.error_count > ?"], '<', ["file_imports.error_count < ?"], '>=', ["file_imports.error_count >= ?"], '<=', ["file_imports.error_count <= ?"]],
    :error_count_min => ActiveSupport::OrderedHash['>=', ["file_imports.error_count >= ?"], '>', ["file_imports.error_count > ?"]],
    :error_count_max => ActiveSupport::OrderedHash['<=', ["file_imports.error_count <= ?"], '<', ["file_imports.error_count < ?"]],
  :log => ActiveSupport::OrderedHash['=~', ["file_imports.log LIKE ?", '%%%s%'], '!~', ["file_imports.log NOT LIKE ?", '%%%s%'], '^=', ["file_imports.log LIKE ?", '%s%'], '$=', ["file_imports.log LIKE ?", '%%%s'], '=', ["file_imports.log = ?"], '!=', ["file_imports.log <> ?"], 'NULL', ["file_imports.log IS NULL", ''], 'NOT_NULL', ["file_imports.log IS NOT NULL", '']]}.freeze
  EXCEL_DATE_REGEXP = /\A\d{2,5}(\.\d*)?\Z/
  FRENCH_DATE_REGEXP = /(\d\d)\/(\d\d)\/(\d\d\d\d)/
  NUM_REGEXP = /\A[+-]?(((\d+(\.)?)|(\d*\.\d+))([eE][+-]?\d+)?)\Z/
  FILES_DEST = Rails.root.join('files', %q{file_imports}).to_s


  # == Validations



  # == Triggers


  after_create :file__after_create_trigger

  after_update :file__after_update_trigger

  after_destroy :file__after_destroy_trigger

  # == Relations
  #


  has_many :re_imports, :foreign_key => "file_import_id", :class_name => "FileImport"
  belongs_to :user, :foreign_key => "user_id", :class_name => "User"
  belongs_to :file_import, :foreign_key => "file_import_id", :class_name => "FileImport"


  # Associations through specific setters
  #
  # Virtual Fields

  attr_accessor :user_was
  attr_accessor :file_import_was
  attr_accessor :re_imports_was


  # == Methods
  #



  # Load the matching object with right attributes.
  #
  # Author:: Sylvain Abélard
  # Version:: 53
  # Last Update:: 2013-09-03 16:56:08 UTC
  # Status:: Validated


  def self.load_from_params(att)
    return FileImport.new if att.blank?
    std_atts = att.reject{|k,v| %w(id user file_import re_imports file file_tmp file_name).include?(k.to_s) }
    file_import = nil
    if att.has_key?(:id) && att[:id].to_i != 0 # Useful for HasOne (ho_assoc)
      file_import = FileImport.find(att[:id])
      file_import.attributes = std_atts
    else
      file_import = FileImport.new(std_atts)
    end

    # clean associations

    file_import.user_load_from_params(att[:user])
    file_import.file_import_load_from_params(att[:file_import])
    file_import.re_imports_load_from_params(att[:re_imports])

    #clean binaries

    file_import.file_load_from_params(att)

    #clean serialized data

    return file_import
  end


  # Search
  #
  # Author:: Yann Azoury
  # Version:: 23
  # Last Update:: 2011-08-09 11:16:42 UTC
  # Status:: Validation Pending


  def self.search(values, comps=nil, opts={})
    ar_opts = {}
    if values.is_a?(SmartQuery)
      ar_opts = values.to_ar_opts
    else
      cond = {}
      inc = []
      string_h = {'=' => nil, '<>' => :ne, '=~' => :like, '!=~' => :not,
        'LIKE' => :eq, 'NOT LIKE' => :ne, 'STARTS WITH' => :starts_with, 'ENDS WITH' => :ends_with,
      'IS NULL' => nil, 'IN' => nil}
      numb_h = {'=' => nil, '<>' => :ne, '>' => :gt, '<' => :lt, '>=' => :gte, '<=' => :lte, 'IS NULL' => nil, 'IN' => nil}
      date_h = {'=' => nil, '<>' => :ne, '>' => :gt, '<' => :lt, '>=' => :gte, '<=' => :lte, 'IS NULL' => nil, 'IN' => nil}
      bin_h = {'is named' => :eq, 'size larger than' => :gte, 'size smaller than' => :lte, 'is not set' => nil}
      assoc_h = {'<>' => :ne, '=' => nil, 'IN' => nil, 'IS NULL' => nil}
      FileImport.new.params_to_attributes(values).each { |k,v|
        case k.to_sym
        when :user_id
          cmp = comps["comp_user_id"]
          cmp ||= 'IN'
          vals  = val.is_a?(Enumerable) ? v : v.split(',').map(&:to_i)
          val   = cmp == 'IS NULL' ? nil : vals

app/views/file_imports/_filter_bar.html.erb
<%;################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Thu Oct 31 16:38:17 +0100 2013
## It should be placed at 'app/views/file_imports/_filter_bar.html.erb'
## All manual modifications will be destroyed on next generation
################################################ %>


  <% @file_import ||= FileImport.new %>

  <form id="file_imports_filter_form" class="filter_bar" cky='<%= cookies[:active_filters] %>'>
    <fieldset>
    <legend><%= _(%q{Filters}) %></legend>
    <div class="clear">
      <input type="reset" id="clear_filters" value="<%= _(%q{Clear}) %>" />
    </div>
    
      <label class="input_bt_assoc" data-field="user_id" for="user_id_for" id="file_imports_user_<%= @file_import.id || 0 %>"><%= s_(%q{User: }) %><select class="not-aligned comparator" id="comp_user_id" name="comp_user_id" style="display:none"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:user] || {}).keys.map{|k| [s_("association|#{k}"), k]}) %></select>
<select name="file_import[<%=  @file_import.id || 0  %>][user_id]" id="file_import_<%= @file_import.id || 0 %>_user_id">
<option value=""><%= _(%q{[All]}) %></option>
<%= options_for_select((@file_import_user__potential_values || @file_import.user__potential_values).map{|p| [p.disp_name, p.id] }, @file_import.user_id) %>
</select></label>
    
    </fieldset>
  </form>

app/views/file_imports/search.html.erb
<%;################################################
## This file and all its content belong to Faveod S.A.S unless a commercial
## contract signed by a representant of Faveod S.A.S states otherwise.
##########
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################
## This has been generated by Faveod Generator on Thu Oct 31 16:38:15 +0100 2013
## It should be placed at 'app/views/file_imports/search.html.erb'
## All manual modifications will be destroyed on next generation
################################################ %>
<h2 class="title"><img src="/images/page_icons/magnifier.png" alt="<%= _(%q{Search}) %>" /> <%= _("Searching %{page}") % {:page => _("File Import")} %> </h2>


<div id="container" class="content align_fields">
<div class="fields">
<form action="<%= "/#{params[:lang]}" if params[:lang] %>/file_imports/search" data-update="search_results" enctype="multipart/form-data" id="file_imports_search_form" method="post">
	<fieldset style="border:none;" id="file_import_<%=  @file_import.id || 0  %>_root_container" >
<fieldset id="file_import_<%=  @file_import.id || 0  %>_import" >
<legend for="file_import_<%=  @file_import.id || 0  %>_import" id="file_imports_import_<%= @file_import.id || 0 %>"><%= s_(%q{Import}) %></legend>
<label class="input_bt_assoc" data-field="user_id" for="user_id_for" id="file_imports_user_<%= @file_import.id || 0 %>"><%= s_(%q{User: }) %><select class="not-aligned comparator" id="comp_user_id" name="comp_user_id"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:user] || {}).keys.map{|k| [s_("association|#{k}"), k]}) %></select>
<select name="file_import[<%=  @file_import.id || 0  %>][user_id]" id="file_import_<%= @file_import.id || 0 %>_user_id">
<option value=""><%= _(%q{[All]}) %></option>
<%= options_for_select((@file_import_user__potential_values || @file_import.user__potential_values).map{|p| [p.disp_name, p.id] }, @file_import.user_id) %>
</select></label>
<label class="input_binary" data-field="file" for="file_for" id="file_imports_file_<%= @file_import.id || 0 %>"><%= s_(%q{File: }) %><select class="not-aligned comparator" id="comp_file" name="comp_file"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:file] || {}).keys.map{|k| [s_("binary|#{k}"), k]}) %></select>
<input id="file_import_<%=  @file_import.id || 0  %>_file" name="file_import[<%=  @file_import.id || 0  %>][file]" type="text" /></label>
<label class="input_bt_assoc" data-field="file_import_id" for="file_import_id_for" id="file_imports_file_import_<%= @file_import.id || 0 %>"><%= s_(%q{File Import: }) %><select class="not-aligned comparator" id="comp_file_import_id" name="comp_file_import_id"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:file_import] || {}).keys.map{|k| [s_("association|#{k}"), k]}) %></select>
<select name="file_import[<%=  @file_import.id || 0  %>][file_import_id]" id="file_import_<%= @file_import.id || 0 %>_file_import_id">
<option value=""><%= _(%q{[All]}) %></option>
<%= options_for_select((@file_import_file_import__potential_values || @file_import.file_import__potential_values).map{|p| [p.disp_name, p.id] }, @file_import.file_import_id) %>
</select></label>
<label class="input_hm_assoc" data-field="re_imports" for="re_imports_for" id="file_imports_re_imports_<%= @file_import.id || 0 %>"><%= s_(%q{Re-imports: }) %><select class="not-aligned comparator" id="comp_re_imports" name="comp_re_imports"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:re_imports] || {}).keys.map{|k| [s_("association|#{k}"), k]}) %></select>
<select multiple="true" size="8" name="file_import[<%=  @file_import.id || 0  %>][re_imports][]" id="file_import_<%= @file_import.id || 0 %>_re_imports">
<option value=""><%= _(%q{[All]}) %></option>
<%= options_for_select((@file_import_re_imports__potential_values || @file_import.re_imports__potential_values).map{|p| [p.disp_name, p.id] }, @file_import.re_import_ids) %>
</select></label>
</fieldset>

<fieldset id="file_import_<%=  @file_import.id || 0  %>_progress_cont" >
<legend for="file_import_<%=  @file_import.id || 0  %>_progress_cont" id="file_imports_progress_cont_<%= @file_import.id || 0 %>"><%= s_(%q{Progress}) %></legend>
<label class="input_datetime" data-field="started_at" for="started_at_for" id="file_imports_started_at_<%= @file_import.id || 0 %>"><%= s_(%q{Started at: }) %><select class="not-aligned comparator" id="comp_started_at" name="comp_started_at"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:started_at] || {}).keys.map{|k| [s_("datetime|#{k}"), k]}) %></select>
<input class="calendar" id="file_import_<%=  @file_import.id || 0  %>_started_at" name="file_import[<%=  @file_import.id || 0  %>][started_at]" type="text" /></label>
<label class="input_datetime" data-field="completed_at" for="completed_at_for" id="file_imports_completed_at_<%= @file_import.id || 0 %>"><%= s_(%q{Completed at: }) %><select class="not-aligned comparator" id="comp_completed_at" name="comp_completed_at"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:completed_at] || {}).keys.map{|k| [s_("datetime|#{k}"), k]}) %></select>
<input class="calendar" id="file_import_<%=  @file_import.id || 0  %>_completed_at" name="file_import[<%=  @file_import.id || 0  %>][completed_at]" type="text" /></label>
<label class="input_integer" data-field="read_lines" for="read_lines_for" id="file_imports_read_lines_<%= @file_import.id || 0 %>"><%= s_(%q{Read lines: }) %><select class="not-aligned comparator" id="comp_read_lines" name="comp_read_lines"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:read_lines] || {}).keys.map{|k| [s_("integer|#{k}"), k]}) %></select>
<input id="file_import_<%= @file_import.id || 0 %>_read_lines" name="file_import[<%=  @file_import.id || 0  %>][read_lines]" type="text" value="<%=h @file_import.read_lines %>" /></label>
<label class="input_integer" data-field="wrote_records" for="wrote_records_for" id="file_imports_wrote_records_<%= @file_import.id || 0 %>"><%= s_(%q{Wrote Records: }) %><select class="not-aligned comparator" id="comp_wrote_records" name="comp_wrote_records"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:wrote_records] || {}).keys.map{|k| [s_("integer|#{k}"), k]}) %></select>
<input id="file_import_<%= @file_import.id || 0 %>_wrote_records" name="file_import[<%=  @file_import.id || 0  %>][wrote_records]" type="text" value="<%=h @file_import.wrote_records %>" /></label>
<label class="input_integer" data-field="expected_total" for="expected_total_for" id="file_imports_expected_total_<%= @file_import.id || 0 %>"><%= s_(%q{Expected total: }) %><select class="not-aligned comparator" id="comp_expected_total" name="comp_expected_total"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:expected_total] || {}).keys.map{|k| [s_("integer|#{k}"), k]}) %></select>
<input id="file_import_<%= @file_import.id || 0 %>_expected_total" name="file_import[<%=  @file_import.id || 0  %>][expected_total]" type="text" value="<%=h @file_import.expected_total %>" /></label>
<label class="input_integer" data-field="error_count" for="error_count_for" id="file_imports_error_count_<%= @file_import.id || 0 %>"><%= s_(%q{Error Count: }) %><select class="not-aligned comparator" id="comp_error_count" name="comp_error_count"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:error_count] || {}).keys.map{|k| [s_("integer|#{k}"), k]}) %></select>
<input id="file_import_<%= @file_import.id || 0 %>_error_count" name="file_import[<%=  @file_import.id || 0  %>][error_count]" type="text" value="<%=h @file_import.error_count %>" /></label>
</fieldset>

<fieldset id="file_import_<%=  @file_import.id || 0  %>_log_cont" >
<legend for="file_import_<%=  @file_import.id || 0  %>_log_cont" id="file_imports_log_cont_<%= @file_import.id || 0 %>"><%= s_(%q{Log}) %></legend>
<label class="input_text" data-field="log" for="log_for" id="file_imports_log_<%= @file_import.id || 0 %>"><%= s_(%q{Log: }) %><select class="not-aligned comparator" id="comp_log" name="comp_log"><%= options_for_select([['','']]+(FileImport::COMPARATORS[:log] || {}).keys.map{|k| [s_("text|#{k}"), k]}) %></select>
<textarea cols="60" id="file_import_<%= @file_import.id || 0 %>_log" name="file_import[<%=  @file_import.id || 0  %>][log]"><%= @file_import.log %></textarea></label>
</fieldset>

</fieldset>

  <input disable_with="" id="search_search_form_submit" name="commit" type="submit" value="<%= _(%q{Search}) %>" />
</form>
</div>
<div id="search_results"></div>
</div>

<% if @pres_mode == :list_zoom %>
<a href="#" data-method="get" onclick="new Ajax.Updater('file_imports_element', '<%= "/#{params[:lang]}" if params[:lang] %>/file_imports/index', {asynchronous:true, evalScripts:true}); return false;" rel="nofollow" title="<%= _(%q{Index of all file_imports.}) %>"><img src="/images/page_icons/server_compressed.png" alt="<%= _(%q{Back}) %>" title="<%= _(%q{Back}) %>"/> <%= _(%q{Back}) %></a>
<% else %>
<a href="<%= "/#{params[:lang]}" if params[:lang] %>/file_imports/index" data-method="get" rel="nofollow" title="<%= _(%q{Index of all file_imports.}) %>"><img src="/images/page_icons/server_compressed.png" alt="<%= _(%q{Back}) %>" title="<%= _(%q{Back}) %>"/> <%= _(%q{Back}) %></a>
<% end %>


<script type="text/javascript">
//<![CDATA[



function onready_search_call() {

$('#file_imports_search_form').on('submit', function(evt) {
  var upd = $(this).data('update');
  evt.preventDefault();
  $.post(this.action, {query:Storage.jsonify_form(this)}).success(function(r) { $('#'+upd).html(r); });
})

}
<% if request.xhr? %>onready_search_call();<% else %> if (document.observe) {
document.observe('dom:loaded', onready_search_call)
} else if (typeof(jQuery) != 'undefined') {
jQuery(document).ready(onready_search_call)
}<% end %>




//]]>
</script>